### ISSUE TITLE
Hacktoberfest: Ideas for Github Actions Workflow

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/set-brightness#3]
# Hacktoberfest 2020
 
1.  A workflow to run basic test on pull request.
2. A workflow to check against shell script analysis (e.g: https://www.shellcheck.net/) on pull request. 

Useful GitHub Actions:
* `reviewdog/action-spellcheck`

If you are interested to work on these or have new ideas, let me know in the comment and start submit the pull request.

Puru,
Happy Hacking

**Comment by raydwaipayan** [comment]
We can use reviewdog/action-spellcheck for it probably. They are also offering some linting tools.
