### ISSUE TITLE
Hacktoberfest 2020: Add support for other Laptop and display hardware

### ISSUE THREAD

**Issue by tuladhar** [tuladhar/set-brightness#4]
# Hacktoberfest 2020: Add support for more display

At the moment, `set-brightness` only supports Intel display and might not work follow files are not present in the system. 

```
MAX_BRIGHTNESS_PATH=/sys/class/backlight/intel_backlight/max_brightness
SET_BRIGHTNESS_PATH=/sys/class/backlight/intel_backlight/brightness
```

This works well for Dell laptops, but we want to also have `set-brightness` work on Laptops other than Dell with different display hardware.

### Acceptance Criteria
1. Check if `set-brightness` works on other Dell machines if you have one. **(Difficulties: Easy)**
2. If `set-brightness` doesn't' work on your Laptop. Share the output of `ls -lh /sys/class/backlight` so other's can fix it.  **(Difficulties: Easy)**
3. (optional) Submit PR with the fix to work with that display. **(Difficulties: Medium)**

- - -
Stay Safe & Happy Hacking,
Puru

**Comment by raydwaipayan** [comment]
We can have checks to determine the actual controller.

For example, some systems have the brightness controller in `/sys/class/backlight/acpi_video0/brigthness`

I can take it up!
